# Generated by Django 5.2.7 on 2026-04-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10)),
                ('rollno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('sclass', models.CharField(max_length=30)),
                ('tclass', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=1)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('cid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('roomno', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('doc', models.FileField(upload_to='')),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=15)),
                ('contactno', models.CharField(max_length=20)),
                ('emailaddress', models.EmailField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('sclass', models.CharField(max_length=30)),
                ('feespaid', models.CharField(max_length=10)),
                ('duefees', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=30)),
                ('sclass', models.CharField(max_length=50)),
                ('book', models.CharField(max_length=50)),
                ('steacher', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=15)),
                ('contactno', models.CharField(max_length=20)),
                ('emailaddress', models.EmailField(max_length=50, unique=True)),
                ('tclass', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('salary', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
