# Generated by Django 5.1.1 on 2024-09-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=30)),
                ('sclass', models.CharField(max_length=50)),
                ('book', models.CharField(max_length=50)),
                ('steacher', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
