# Generated by Django 5.1.1 on 2024-09-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.CharField(max_length=15)),
                ('contactno', models.IntegerField(max_length=13)),
                ('emailaddress', models.EmailField(max_length=50)),
                ('tclass', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('salary', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
