# Generated by Django 5.1.1 on 2024-09-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
