# Generated by Django 5.1.1 on 2024-09-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_attendence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
