# Generated by Django 5.1.1 on 2024-09-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_delete_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10)),
                ('rollno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('sclass', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=1)),
                ('created_date', models.DateField()),
            ],
        ),
    ]
