# Generated by Django 5.1.1 on 2024-09-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_attendence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
