# Generated by Django 3.2.4 on 2024-09-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_adminlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLogin',
        ),
    ]
