# Generated by Django 5.2.7 on 2026-04-17 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sm', models.FileField(upload_to='')),
                ('tclass', models.CharField(max_length=30)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacher', to_field='emailaddress')),
            ],
        ),
    ]
