# Generated by Django 5.1.1 on 2024-09-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyMaterial',
        ),
    ]
